openapi: 3.1.0
info:
  title: Forbidden Words Checker API
  version: 1.0.0
  description: |
    API voor het controleren van verboden woorden in documenten.
    Ondersteunt PDF en DOCX bestanden tot 25MB.
  contact:
    name: Jordi Eke
    email: jordi@eke.nl

servers:
  - url: https://forbidden-words-checker-2.onrender.com
    description: Production server

paths:
  /health:
    get:
      operationId: checkHealth
      summary: Controleer de gezondheid van de API
      responses:
        '200':
          description: API is gezond en actief
          content:
            text/plain:
              schema:
                type: string
                example: OK

  /check:
    post:
      operationId: checkDocument
      summary: Controleer een document op verboden woorden
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: PDF of DOCX bestand om te controleren (max 25MB)
      responses:
        '200':
          description: Succesvolle controle
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        word:
                          type: string
                          description: Het gevonden verboden woord
                        context:
                          type: string
                          description: Context waarin het woord gevonden is
        '400':
          description: Ongeldige aanvraag
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server fout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 