services:
  - type: web
    name: forbidden-words-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: API_SECRET_KEY
        generateValue: true
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_ORIGINS
        value: https://chat.openai.com,https://chatgpt.com
      - key: BASE_URL
        value: https://forbidden-words-checker-2.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 